# Generated by Django 3.2.12 on 2023-08-12 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='cname',
            field=models.CharField(max_length=100),
        ),
    ]
